// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TournamentLadder.Infrastructure.Context;

#nullable disable

namespace TournamentLadder.Infrastructure.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20220701110238_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("TournamentLadder.Infrastructure.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfUpdate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LadderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamScores")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LadderId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("TournamentLadder.Infrastructure.Entities.Ladder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfUpdate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ladder");
                });

            modelBuilder.Entity("TournamentLadder.Infrastructure.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("TournamentLadder.Infrastructure.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("TournamentLadder.Infrastructure.Entities.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfUpdate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LadderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TournamentEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("TournamentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TournamentStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LadderId");

                    b.ToTable("Tournament");
                });

            modelBuilder.Entity("TournamentLadder.Infrastructure.Entities.Game", b =>
                {
                    b.HasOne("TournamentLadder.Infrastructure.Entities.Ladder", null)
                        .WithMany("Games")
                        .HasForeignKey("LadderId");
                });

            modelBuilder.Entity("TournamentLadder.Infrastructure.Entities.Member", b =>
                {
                    b.HasOne("TournamentLadder.Infrastructure.Entities.Team", null)
                        .WithMany("Members")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("TournamentLadder.Infrastructure.Entities.Team", b =>
                {
                    b.HasOne("TournamentLadder.Infrastructure.Entities.Tournament", null)
                        .WithMany("TournamentTeams")
                        .HasForeignKey("TournamentId");
                });

            modelBuilder.Entity("TournamentLadder.Infrastructure.Entities.Tournament", b =>
                {
                    b.HasOne("TournamentLadder.Infrastructure.Entities.Ladder", "Ladder")
                        .WithMany()
                        .HasForeignKey("LadderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ladder");
                });

            modelBuilder.Entity("TournamentLadder.Infrastructure.Entities.Ladder", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("TournamentLadder.Infrastructure.Entities.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("TournamentLadder.Infrastructure.Entities.Tournament", b =>
                {
                    b.Navigation("TournamentTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
